### ISSUE TITLE
怎样使用该主题呢

### ISSUE THREAD

**Issue by duskdusts** [Octobug/blog#24]
博主的主题看起来很舒服，能告诉一下如何快捷使用您的主题吗

**Comment by Octobug** [comment]
@duskdusts 感谢关注。README 中有提到：

> This project is not going to be made an out-of-the-box blog theme. It's a very personal project, but any helps and advice are welcome.

你可以直接 clone 这个项目到本地，并修改成你自己的博客仓库。开发环境的配置参见 README 中的 contribution 部分。

我认为博客是非常个人化的站点，不太可能一个主题适合很多个人，而做成可配置化需要很多额外的精力，所以我不打算做成开箱即用的主题。（建议 clone 一份自己改改
